/// Flutter icons CPOUnits
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CPOUnits
///      fonts:
///       - asset: fonts/CPOUnits.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CPOUnits {
  CPOUnits._();

  static const _kFontFam = 'CPOUnits';
  static const String? _kFontPkg = null;

  static const IconData mts = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kw = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData okCircle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacyPolicy = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteAccount = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helpSupport = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmarkEmpty = IconData(0xf097, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationArrow = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
